### ISSUE TITLE
VerifyError?

### ISSUE THREAD

**Issue by gregko** [davide-imbriaco/a-sync-browser#13]
I tried to build it myself from GitHub repo, the build went fine, but upon startup I get a crash, a VerifyError. I cannot even guess what it is and why, could someone give me a hint at least? Seems to be something about a DB connectivity:

Here is the stack trace:

 E/Main: error
                                         com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: General error: "java.lang.VerifyError: org.h2.mvstore.db.TransactionStore$TransactionMap" [50000-193]
                                             at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:514)
                                             at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:107)
                                             at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
                                             at it.anyplace.sync.repository.repo.SqlRepository.<init>(SqlRepository.java:125)
                                             at it.anyplace.sync.client.SyncthingClient.<init>(SyncthingClient.java:68)
                                             at it.anyplace.syncbrowser.MainActivity.initClient(MainActivity.java:146)
                                             at it.anyplace.syncbrowser.MainActivity.-wrap7(MainActivity.java)
                                             at it.anyplace.syncbrowser.MainActivity$15.doInBackground(MainActivity.java:379)
                                             at it.anyplace.syncbrowser.MainActivity$15.doInBackground(MainActivity.java:377)
                                             at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                             at java.lang.Thread.run(Thread.java:818)

**Comment by Enrico204** [comment]
Hi @gregko , I cloned the repository locally and I have no issues on build. Do you still have this error?

**Comment by gregko** [comment]
Don't know, gave up on a-sync-browser and deleted my build tree, sorry...
